### ISSUE TITLE
BaseOptionModel ArgumentNullException in Tweakster output tab during startup

### ISSUE THREAD

**Issue by karaziox** [madskristensen/Tweakster#30]
When I start Visual Studio I can see a dozen times the same exception appear in the output:

> System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at Tweakster.BaseOptionModel\`1.DeserializeValue(String value, Type type) in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 162
   at Tweakster.BaseOptionModel`1.<LoadAsync>d__11.MoveNext() in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 94

Unsure if it is related but I'm using VS 16.8 Preview 1. It seems to do that every time I launch it.

**Comment by msedi** [comment]
Having the same problem

```
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at Tweakster.BaseOptionModel`1.DeserializeValue(String value, Type type) in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 162
   at Tweakster.BaseOptionModel`1.<LoadAsync>d__11.MoveNext() in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 94

System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at Tweakster.BaseOptionModel`1.DeserializeValue(String value, Type type) in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 162
   at Tweakster.BaseOptionModel`1.<LoadAsync>d__11.MoveNext() in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 94

System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at Tweakster.BaseOptionModel`1.DeserializeValue(String value, Type type) in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 162
   at Tweakster.BaseOptionModel`1.<LoadAsync>d__11.MoveNext() in C:\projects\tweakster\src\Options\BaseOptionModel.cs:line 94
```
