### ISSUE TITLE
Adding an entity to an entity framework edmx and saving leads to an exception

### ISSUE THREAD

**Issue by ite-klass** [madskristensen/Tweakster#34]
```
System.Threading.ThreadAbortException: Thread was being aborted.
   at EnvDTE.Project.Save(String FileName)
   at Tweakster.AutoSave.OnProjectItemChange(ProjectItem item) in C:\projects\tweakster\src\Tweaks\General\AutoSave.cs:line 63
```

VS Pro 16.7.2
Tweaks 1.0.83

Saving the edmx triggers a T4 text template transformation.

Adding columns to existing entities was no problem (update model from database). It may have to do with the new cs file being added to the project(?).

I have not tested with variance to see if this is only in specific cases or adding any entity.

**Comment by ite-klass** [comment]
The issue still exists.

Did that code change merely remove logging information without fixing the actual issue?

It still works fine with the extension disabled.

![image](https://user-images.githubusercontent.com/8045680/92615065-0253ab80-f2bd-11ea-82cb-96e17dd509f1.png)
