### ISSUE TITLE
Errors on VS launch after update to VS 16.11.0

### ISSUE THREAD

**Issue by MikeFarrington** [madskristensen/Tweakster#86]
I get the following in the Extensions Output window on launch of Visual Studio after updating to 16.11.0 (released one day before this issue was created).  This is using the latest available 1.1.125 from the extensions manager.

```
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:ShowBuildStats dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:DeleteOuputArtifactsOnClean dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:ShowBuildOrder dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:DebugOnF10F11 dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CloseTabOnControlW dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:RunCodeCleanupOnFormat dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CollapseMemberAttributes dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CollapseMemberAttributesShortForm dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:EnableZoomOnScroll dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CopyEmptySelection dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CopyEmptyLines dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:FormatOnMoveLine dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:DefaultZoomLevel dataType:Int32 PropertyType:System.Int32 Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:CopyWithoutIndentation dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:WarnOnPaste dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:FocusSolutionExplorerOnProjectLoad dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:AutoSave dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:SaveAllOnBuild dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:EnablePresentationMode dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)
BaseOptionModel<Tweakster.Options>.Load CollectionName:Tweakster.Options PropertyName:EnableSafeMode dataType:Int32 PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetInt32(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.<>c__DisplayClass8_0`1.<CreateSettingsStoreGetMethod>b__0(SettingsStore settingsStore, String collectionName, String propertyName)
   at Community.VisualStudio.Toolkit.OptionModelPropertyWrapper.Load[TOptMdl](BaseOptionModel`1 baseOptionModel, SettingsStore settingsStore)

**Comment by MikeFarrington** [comment]
Yes, thank you, I discovered that on my own and was about to report my findings.  Though, after doing so, Visual Studio keeps complaining about this extension's startup time, complaining that it's taking 9s on a very well spec'd computer.
